Repository 5GSEC/nimbus, pull requests merged in 2024-02, with the labels that each got.

#48 docs: Update quick-tutorials and examples
  docs/getting-started.md
  docs/quick-tutorials.md
  examples/env/nginx-deploy.yaml
  examples/namespaced/dns-manipulation-si-sib.yaml
  examples/namespaced/multiple-si-sib-namespaced.yaml
  examples/namespaced/pkg-mgr-exec-si-sib.yaml
  scripts/cleanup.sh
  test/env/busybox-pod.yaml
  test/env/multiubuntu.yaml
  test/env/redis-pod.yaml
  test/v1/intents/network/intent-net-icmp-audit.yaml
  test/v1/intents/network/intent-network-sample.yaml
  test/v1/intents/network/intent-redis.yaml
  test/v1/intents/network/intent-risky-network-access.yaml
  test/v1/intents/system/intent-accessd-shadow-file.yaml
  test/v1/intents/system/intent-allow-access-to-credentials-dir.yaml
  test/v1/intents/system/intent-bug-block.yaml
  test/v1/intents/system/intent-cap-net-raw-block.yaml
  test/v1/intents/system/intent-do-not-allow-priv-escalation.yaml
  test/v1/intents/system/intent-path-block.yaml
  test/v1/intents/system/intent-restrict-write-access-to-sys-folders.yaml
  test/v1/intents/template-intent.yaml
  test/v1/policy/cnp/policy-redis.yaml
  test/v1/policy/cnp/policy-risky.yaml
  test/v1/policy/hsp/policy-accessed-shadow-file.yaml
  test/v1/policy/hsp/policy-bug-block.yaml
  test/v1/policy/ksp/policy-audit-all-unlink.yaml
  test/v1/policy/ksp/policy-cap-net-raw-block.yaml
  test/v1/policy/ksp/policy-file-dir-allow-from-source-path.yaml
  test/v1/policy/ksp/policy-net-icmp-audit.yaml
  test/v1/policy/ksp/policy-path-block.yaml
  test/v1/policy/ksp/policy-proc-dir-block.yaml
  test/v2/bindings/network/binding-redis.yaml
  test/v2/bindings/system/binding-path-block.yaml
  test/v2/clusterscoped/multiple-si-sib.yaml
  test/v2/clusterscoped/si-sib.yaml
  test/v2/intents/network/intent-redis.yaml
  test/v2/intents/system/intent-path-block.yaml
Labels: documentation

#53 feat(adapters): Reconcilation for native policies
  .github/workflows/pr-checks.yaml
  pkg/adapter/common/common.go
  pkg/adapter/k8s/client.go
  pkg/adapter/nimbus-kubearmor/go.mod
  pkg/adapter/nimbus-kubearmor/main.go
  pkg/adapter/nimbus-kubearmor/manager/kspmanager.go
  pkg/adapter/nimbus-kubearmor/manager/manager.go
  pkg/adapter/nimbus-kubearmor/watcher/kspwatcher.go
  pkg/adapter/nimbus-netpol/go.mod
  pkg/adapter/nimbus-netpol/main.go
  pkg/adapter/nimbus-netpol/manager/netpols_manager.go
  pkg/adapter/nimbus-netpol/watcher/netpolwatcher.go
  pkg/adapter/util/nimbuspolicy_util.go
  pkg/adapter/util/watcher_util.go
  pkg/adapter/watcher/clusternimbuspolicy_watcher.go
  pkg/adapter/watcher/nimbuspolicy_watcher.go
Labels: enhancement

#67 fix(adapters): Update SwDeploymentTools KSP to include apk pkg manager
  pkg/adapter/nimbus-kubearmor/processor/kspbuilder.go
Labels: bug

#66 added integration tests
  .github/workflows/pr-checks.yaml
  Makefile
  go.mod
  go.sum
  internal/controller/suite_test.go
  tests/chainsaw-config.yaml
  tests/controllers/nimbuspolicy/delete/README.md
  tests/controllers/nimbuspolicy/delete/chainsaw-test.yaml
  tests/controllers/nimbuspolicy/nimbus-policy-assert.yaml
  tests/controllers/nimbuspolicy/update/README.md
  tests/controllers/nimbuspolicy/update/chainsaw-test.yaml
  tests/controllers/nimbuspolicy/updated-nimbus-policy.yaml
  tests/controllers/resources/namespaced/1-dns-manipulation-si.yaml
  tests/controllers/resources/namespaced/1-dns-manipulation-sib.yaml
  tests/controllers/securityintent/README.md
  tests/controllers/securityintent/chainsaw-test.yaml
  tests/controllers/securityintent/si-status-assert.yaml
  tests/controllers/securityintentbinding/create/README.md
  tests/controllers/securityintentbinding/create/chainsaw-test.yaml
  tests/controllers/securityintentbinding/delete/README.md
  tests/controllers/securityintentbinding/delete/chainsaw-test.yaml
  tests/controllers/securityintentbinding/nimbus-policy-assert.yaml
  tests/controllers/securityintentbinding/np-status-assert.yaml
  tests/controllers/securityintentbinding/sib-status-assert.yaml
  tests/controllers/securityintentbinding/update/README.md
  tests/controllers/securityintentbinding/update/chainsaw-test.yaml
  tests/controllers/securityintentbinding/updated-np.yaml
  tests/controllers/securityintentbinding/updated-sib.yaml
Labels: test
